code --install-extension~ anseki.vscode-color
code --install-extension~ circlecodesolution.ccs-flutter-color
code --install-extension~ Dart-Code.dart-code
code --install-extension~ Dart-Code.flutter
code --install-extension~ davidwoo.flutter-auto-import
code --install-extension~ dbaeumer.vscode-eslint
code --install-extension~ Durzn.brackethighlighter
code --install-extension~ eamodio.gitlens
code --install-extension~ esbenp.prettier-vscode
code --install-extension~ Gruntfuggly.todo-tree
code --install-extension~ johnsoncodehk.volar
code --install-extension~ marcelovelasquez.flutter-tree
code --install-extension~ mosapride.zenkaku
code --install-extension~ ms-azuretools.vscode-docker
code --install-extension~ MS-CEINTL.vscode-language-pack-ja
code --install-extension~ natqe.reload
code --install-extension~ octref.vetur
code --install-extension~ oderwat.indent-rainbow
code --install-extension~ shardulm94.trailing-spaces
code --install-extension~ SonarSource.sonarlint-vscode
code --install-extension~ wmaurer.change-case
